<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-TRL4B08" failures="1" tests="7" name="Default test" time="28.078" errors="0" timestamp="2023-01-08T15:07:06 BDT">
  <testcase classname="test.com.TextExecution" name="lunchURL" time="7.922"/>
  <testcase classname="test.com.TextExecution" name="loginToSite" time="2.389"/>
  <testcase classname="test.com.TextExecution" name="addEmployee" time="13.607">
    <failure type="java.lang.AssertionError" message="Employee Not Added Successfully expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Employee Not Added Successfully expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertTrue(Assert.java:56)
at page.com.PIMPage.addEmployee(PIMPage.java:84)
at test.com.TextExecution.addEmployee(TextExecution.java:58)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- addEmployee -->
  <testcase classname="test.com.TextExecution" name="openDirectory" time="0.001">
    <skipped/>
  </testcase> <!-- openDirectory -->
  <testcase classname="test.com.TextExecution" name="setSearchCriteria" time="0.001">
    <skipped/>
  </testcase> <!-- setSearchCriteria -->
  <testcase classname="test.com.TextExecution" name="performSearch" time="0.0">
    <skipped/>
  </testcase> <!-- performSearch -->
  <testcase classname="test.com.TextExecution" name="verifySearch" time="0.001">
    <skipped/>
  </testcase> <!-- verifySearch -->
</testsuite> <!-- Default test -->
